---
apiVersion: v1
kind: Service
metadata:
  name: myhero-data
  labels:
    app: myhero
    tier: data
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: myhero
    tier: data
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myhero-data
  annotations:
    opflex.cisco.com/endpoint-group: '{"tenant":"<PROVIDE_ACI_TENANT>","app-profile":"myHero","name":"myHeroData"}'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myhero
        tier: data
    spec:
      containers:
      - name: myhero-data
        image: 10.139.13.50:443/myhero/data:latest
        livenessProbe:
          httpGet:
            path: /hero_list
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /hero_list
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
          - name: myhero_data_key
            value: SecureData
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 64M
      restartPolicy: Always