apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: deployment
metadata:
  name: frontend
  annotations:
    opflex.cisco.com/endpoint-group: {
    "policy-space": "ccp01",
    "name": "guestbook|guestbook-backend"
  }
  