---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myhero-ernst
  annotations:
    opflex.cisco.com/endpoint-group: '{"tenant":"ccp894fbbccf831","app-profile":"myHero","name":"myHeroErnst"}'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myhero
        tier: ernst
    spec:
      containers:
      - name: myhero-ernst
        image: 10.139.12.51/myhero/ernst:latest
        env:
          - name: myhero_mqtt_host
            value: myhero-mosca
          - name: myhero_mqtt_port
            value: "1883"
          - name: myhero_data_srv
            value: myhero-data
          - name: myhero_data_key
            value: SecureData
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 32M
      restartPolicy: Always
